language: node_js
node_js:
  - "4.2.2"
  
before_install:
  - npm install -g npm
  - npm install -g bower
  
before_script:
  - npm install -g gulp
  
script: 
  - gulp jshint
  - gulp jscs
  - gulp test:client
